// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.user_id", "de15bcae-521f-4236-aa22-ee9440dc7e4c");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1618166863);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1618166840);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1618166837);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 3823);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1595117188);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.activity-stream.discoverystream.rec.impressions", "{\"90018\":1618166841863,\"90038\":1618166841894,\"24717479\":1618166841907}");
user_pref("browser.newtabpage.activity-stream.discoverystream.spoc.impressions", "{\"16957663\":[1618166841896]}");
user_pref("browser.newtabpage.activity-stream.impressionId", "{2cbc44d6-5159-4aec-a15f-f552508eeeba}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "amazon");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://amazon.com\",\"label\":\"@amazon\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1618166841136");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1618188441136");
user_pref("browser.search.region", "US");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20200708170202");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1618166840");
user_pref("browser.slowStartup.averageTime", 4768);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20200708170202");
user_pref("browser.startup.homepage_override.mstone", "78.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1618166835);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1618166844808");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "78.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "95498c612e1a4bc3a95f54af780ae2f4");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "78.0.2");
user_pref("extensions.lastPlatformVersion", "78.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"32c7ac11-a477-4af4-bcd3-609ff9001bc9\",\"formautofill@mozilla.org\":\"42237a5e-b758-4cae-8649-fddec33fbf55\",\"screenshots@mozilla.org\":\"f09bd16b-850d-4b2a-a204-8aa0a49c0bee\",\"webcompat-reporter@mozilla.org\":\"64dae588-263b-436d-b0c5-52be97d5543c\",\"webcompat@mozilla.org\":\"383bf22c-bd2d-41b4-ab7b-b2cbcd57146c\",\"default-theme@mozilla.org\":\"265fcc20-d73a-492e-984f-bf91b5a7da3a\",\"google@search.mozilla.org\":\"68d7311e-bc6e-4e89-8e27-5f369fa66fe6\",\"amazondotcom@search.mozilla.org\":\"a4cdb882-03a8-466f-9739-fc5508a6b769\",\"bing@search.mozilla.org\":\"1a1affb1-d5b5-4424-ba1b-b56adcecd0c3\",\"ddg@search.mozilla.org\":\"5d91bd5c-323c-4836-856a-7f62530ac962\",\"ebay@search.mozilla.org\":\"50fd2816-b98d-4436-81e8-26261adad484\",\"twitter@search.mozilla.org\":\"1b8ab641-58cd-4174-bf61-bc2c1588ee69\",\"wikipedia@search.mozilla.org\":\"1a97ddc4-5b76-45ef-8bcb-9492c70decfe\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 12939);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "7c6c4fe7-edfc-4ca3-94ab-a8d08669169c");
user_pref("security.sandbox.plugin.tempDirSuffix", "fc49593d-a22a-4059-9bf9-dbf920994888");
user_pref("services.sync.engine.addresses.available", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1618166830);
user_pref("toolkit.telemetry.cachedClientID", "1f8c9094-ce29-4634-b633-b0689d69c71b");
user_pref("toolkit.telemetry.previousBuildID", "20200708170202");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
